/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://pa7oe6dwxvctroiw2eg2zngqte.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-dpwuivo3hzh7vp4b4nrzbyuzue",
    "aws_cognito_identity_pool_id": "us-east-1:1846fb7c-303d-4840-b312-2e7a6f86b7a6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_1QFbaGqYX",
    "aws_user_pools_web_client_id": "12389a14hvmntvfosb4ab80tfs",
    "oauth": {}
};


export default awsmobile;
